package orchestration

import (
	"context"
	"fmt"
	"maps"
	"sync"
	"time"
)

// Executor is the single interface of the orchestration system.
// Everything that can participate in a Pipeline implements this interface:
// AgentAdapter, AgentBlocksAdapter, ParallelGroup, nested Pipeline,
// or any caller-defined pure logic.
type Executor interface {
	RunWithContext(ctx context.Context, sc *StageContext) error
}

// KeyCollisionError is recorded when two stages write to the same key in a
// StageContext created with NewStrictStageContext.
// Retrieve all collisions after execution via StageContext.CollisionErrors.
type KeyCollisionError struct {
	// Key is the output or artifact key written more than once.
	Key string
	// Namespace is "output" or "artifact".
	Namespace string
}

func (e *KeyCollisionError) Error() string {
	return fmt.Sprintf("orchestration: strict key collision in %s %q: key already set", e.Namespace, e.Key)
}

// StageContext is the state carrier that travels through the entire pipeline.
// Its internal maps are protected by a read/write mutex so that concurrent
// Executors inside a ParallelGroup can safely call SetOutput and SetArtifact.
//
// Goal is immutable after construction and requires no synchronization.
//
// Two parallel stages writing to the same key produce a non-deterministic
// result — the mutex prevents memory corruption but not logical conflicts.
// Avoiding key collisions is the caller's responsibility. For development,
// use NewStrictStageContext to surface collisions as KeyCollisionError values.
type StageContext struct {
	Goal string

	mu         sync.RWMutex
	outputs    map[string]string
	artifacts  map[string]any
	trace      []StageTrace
	strict     bool
	collisions []error
}

// StageTrace records the execution of a single stage.
type StageTrace struct {
	StageName string
	Duration  time.Duration
	Err       error
}

// NewStageContext constructs a StageContext ready for use.
// Pipeline calls this internally; callers may use it to build a StageContext
// for testing custom Executors outside of a pipeline.
func NewStageContext(goal string) *StageContext {
	return &StageContext{
		Goal:      goal,
		outputs:   make(map[string]string),
		artifacts: make(map[string]any),
	}
}

// NewStrictStageContext constructs a StageContext with collision detection enabled.
// In strict mode, SetOutput and SetArtifact record a KeyCollisionError whenever
// a key is written more than once. Call CollisionErrors after all stages complete
// to retrieve them.
//
// Intended for development and testing — use NewStageContext in production.
func NewStrictStageContext(goal string) *StageContext {
	return &StageContext{
		Goal:      goal,
		outputs:   make(map[string]string),
		artifacts: make(map[string]any),
		strict:    true,
	}
}

// SetOutput stores a text output under key. Safe for concurrent use.
// The value is typically the text generated by an LLM and can be read
// by subsequent stages via RequireOutput.
// In strict mode (NewStrictStageContext), writing an existing key records
// a KeyCollisionError retrievable via CollisionErrors.
func (sc *StageContext) SetOutput(key, value string) {
	sc.mu.Lock()
	defer sc.mu.Unlock()
	if sc.strict {
		if _, exists := sc.outputs[key]; exists {
			sc.collisions = append(sc.collisions, &KeyCollisionError{Key: key, Namespace: "output"})
		}
	}
	sc.outputs[key] = value
}

// Output returns the output stored under key and whether it was found.
// Safe for concurrent use.
func (sc *StageContext) Output(key string) (string, bool) {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	v, ok := sc.outputs[key]
	return v, ok
}

// RequireOutput returns the output stored under key or an error if absent.
// Use in PromptBuilders to detect missing dependencies explicitly rather
// than silently receiving an empty string.
func (sc *StageContext) RequireOutput(key string) (string, error) {
	v, ok := sc.Output(key)
	if !ok {
		return "", fmt.Errorf("orchestration: output %q not found in stage context", key)
	}
	return v, nil
}

// Outputs returns a snapshot copy of all text outputs.
// Safe for concurrent use; the returned map is independent of the
// StageContext and can be iterated freely without holding any lock.
func (sc *StageContext) Outputs() map[string]string {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	snap := make(map[string]string, len(sc.outputs))
	maps.Copy(snap, sc.outputs)
	return snap
}

// SetArtifact stores a typed Go value under key. Safe for concurrent use.
// Artifacts hold structured data (scores, slices, flags) that code consumes
// but that make no sense to pass to an LLM as text.
// In strict mode (NewStrictStageContext), writing an existing key records
// a KeyCollisionError retrievable via CollisionErrors.
func (sc *StageContext) SetArtifact(key string, value any) {
	sc.mu.Lock()
	defer sc.mu.Unlock()
	if sc.strict {
		if _, exists := sc.artifacts[key]; exists {
			sc.collisions = append(sc.collisions, &KeyCollisionError{Key: key, Namespace: "artifact"})
		}
	}
	sc.artifacts[key] = value
}

// Artifact returns the artifact stored under key and whether it was found.
// Safe for concurrent use. For a type-safe retrieval use GetArtifact.
func (sc *StageContext) Artifact(key string) (any, bool) {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	v, ok := sc.artifacts[key]
	return v, ok
}

// Artifacts returns a snapshot copy of all artifacts.
// Safe for concurrent use; the returned map is independent of the
// StageContext and can be iterated freely without holding any lock.
func (sc *StageContext) Artifacts() map[string]any {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	snap := make(map[string]any, len(sc.artifacts))
	maps.Copy(snap, sc.artifacts)
	return snap
}

// Trace returns a snapshot copy of the execution trace.
// Safe for concurrent use.
func (sc *StageContext) Trace() []StageTrace {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	snap := make([]StageTrace, len(sc.trace))
	copy(snap, sc.trace)
	return snap
}

// GetArtifact retrieves a typed artifact from the StageContext.
// Returns an error if the key does not exist or the stored type does not
// match T.
//
// Example:
//
//	deps, err := orchestration.GetArtifact[[]string](sc, "deps")
//	conf, err := orchestration.GetArtifact[float64](sc, "confidence")
func GetArtifact[T any](sc *StageContext, key string) (T, error) {
	v, ok := sc.Artifact(key)
	if !ok {
		var zero T
		return zero, fmt.Errorf("orchestration: artifact %q not found", key)
	}
	typed, ok := v.(T)
	if !ok {
		var zero T
		return zero, fmt.Errorf("orchestration: artifact %q: expected %T, got %T", key, zero, v)
	}
	return typed, nil
}

// CollisionErrors returns a snapshot of key collision errors recorded in strict
// mode. Returns nil when strict mode is disabled or no collisions occurred.
// Safe for concurrent use.
func (sc *StageContext) CollisionErrors() []error {
	sc.mu.RLock()
	defer sc.mu.RUnlock()
	if len(sc.collisions) == 0 {
		return nil
	}
	snap := make([]error, len(sc.collisions))
	copy(snap, sc.collisions)
	return snap
}

// appendTrace appends a StageTrace. Called by Pipeline and ParallelGroup only.
func (sc *StageContext) appendTrace(name string, dur time.Duration, err error) {
	sc.mu.Lock()
	defer sc.mu.Unlock()
	sc.trace = append(sc.trace, StageTrace{
		StageName: name,
		Duration:  dur,
		Err:       err,
	})
}
